export const ElementPropsActionTypes = {
  SET_LOGO_COLOR: 'SET_LOGO_COLOR',
  SET_SECTIONTITLE_COLOR: 'SET_SECTIONTITLE_COLOR',
  SET_SECTIONTITLE_TEXT: 'SET_SECTIONTITLE_TEXT',
  SET_BARS_COLOR: 'SET_BARS_COLOR',
  SET_SOCIAL_COLOR: 'SET_SOCIAL_COLOR' 
}